{"url": "https://api.github.com/repos/pytorch/pytorch/issues/413", "repository_url": "https://api.github.com/repos/pytorch/pytorch", "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/413/labels{/name}", "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/413/comments", "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/413/events", "html_url": "https://github.com/pytorch/pytorch/issues/413", "id": 199123229, "node_id": "MDU6SXNzdWUxOTkxMjMyMjk=", "number": 413, "title": "binaries compiled against newer numpy, but executed with older numpy error out", "user": {"login": "soumith", "id": 1310570, "node_id": "MDQ6VXNlcjEzMTA1NzA=", "avatar_url": "https://avatars0.githubusercontent.com/u/1310570?v=4", "gravatar_id": "", "url": "https://api.github.com/users/soumith", "html_url": "https://github.com/soumith", "followers_url": "https://api.github.com/users/soumith/followers", "following_url": "https://api.github.com/users/soumith/following{/other_user}", "gists_url": "https://api.github.com/users/soumith/gists{/gist_id}", "starred_url": "https://api.github.com/users/soumith/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/soumith/subscriptions", "organizations_url": "https://api.github.com/users/soumith/orgs", "repos_url": "https://api.github.com/users/soumith/repos", "events_url": "https://api.github.com/users/soumith/events{/privacy}", "received_events_url": "https://api.github.com/users/soumith/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 586698444, "node_id": "MDU6TGFiZWw1ODY2OTg0NDQ=", "url": "https://api.github.com/repos/pytorch/pytorch/labels/1hr", "name": "1hr", "color": "d4c5f9", "default": false}, {"id": 424131847, "node_id": "MDU6TGFiZWw0MjQxMzE4NDc=", "url": "https://api.github.com/repos/pytorch/pytorch/labels/bug", "name": "bug", "color": "b60205", "default": true}, {"id": 443484050, "node_id": "MDU6TGFiZWw0NDM0ODQwNTA=", "url": "https://api.github.com/repos/pytorch/pytorch/labels/medium%20priority", "name": "medium priority", "color": "fbca04", "default": false}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 3, "created_at": "2017-01-06T04:42:29Z", "updated_at": "2017-09-19T19:26:16Z", "closed_at": "2017-04-18T21:59:30Z", "author_association": "MEMBER", "body_html": "<pre><code>In [1]: import torch\n^[[A---------------------------------------------------------------------------\nRuntimeError                              Traceback (most recent call last)\nRuntimeError: module compiled against API version 0xa but this version of numpy is 0x9\n---------------------------------------------------------------------------\nImportError                               Traceback (most recent call last)\n&lt;ipython-input-1-c031d3dd82fc&gt; in &lt;module&gt;()\n----&gt; 1 import torch\n\n/Users/chinso/anaconda/lib/python2.7/site-packages/torch/__init__.pyc in &lt;module&gt;()\n     43 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)\n     44\n---&gt; 45 from torch._C import *\n     46\n     47 __all__ += [name for name in dir(_C)\n\nImportError: numpy.core.multiarray failed to import\n</code></pre>", "body_text": "In [1]: import torch\n^[[A---------------------------------------------------------------------------\nRuntimeError                              Traceback (most recent call last)\nRuntimeError: module compiled against API version 0xa but this version of numpy is 0x9\n---------------------------------------------------------------------------\nImportError                               Traceback (most recent call last)\n<ipython-input-1-c031d3dd82fc> in <module>()\n----> 1 import torch\n\n/Users/chinso/anaconda/lib/python2.7/site-packages/torch/__init__.pyc in <module>()\n     43 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)\n     44\n---> 45 from torch._C import *\n     46\n     47 __all__ += [name for name in dir(_C)\n\nImportError: numpy.core.multiarray failed to import", "body": "```\r\nIn [1]: import torch\r\n^[[A---------------------------------------------------------------------------\r\nRuntimeError                              Traceback (most recent call last)\r\nRuntimeError: module compiled against API version 0xa but this version of numpy is 0x9\r\n---------------------------------------------------------------------------\r\nImportError                               Traceback (most recent call last)\r\n<ipython-input-1-c031d3dd82fc> in <module>()\r\n----> 1 import torch\r\n\r\n/Users/chinso/anaconda/lib/python2.7/site-packages/torch/__init__.pyc in <module>()\r\n     43 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)\r\n     44\r\n---> 45 from torch._C import *\r\n     46\r\n     47 __all__ += [name for name in dir(_C)\r\n\r\nImportError: numpy.core.multiarray failed to import\r\n```"}