{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/349081972", "html_url": "https://github.com/pytorch/pytorch/issues/2840#issuecomment-349081972", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/2840", "id": 349081972, "node_id": "MDEyOklzc3VlQ29tbWVudDM0OTA4MTk3Mg==", "user": {"login": "jekbradbury", "id": 11729078, "node_id": "MDQ6VXNlcjExNzI5MDc4", "avatar_url": "https://avatars2.githubusercontent.com/u/11729078?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jekbradbury", "html_url": "https://github.com/jekbradbury", "followers_url": "https://api.github.com/users/jekbradbury/followers", "following_url": "https://api.github.com/users/jekbradbury/following{/other_user}", "gists_url": "https://api.github.com/users/jekbradbury/gists{/gist_id}", "starred_url": "https://api.github.com/users/jekbradbury/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jekbradbury/subscriptions", "organizations_url": "https://api.github.com/users/jekbradbury/orgs", "repos_url": "https://api.github.com/users/jekbradbury/repos", "events_url": "https://api.github.com/users/jekbradbury/events{/privacy}", "received_events_url": "https://api.github.com/users/jekbradbury/received_events", "type": "User", "site_admin": false}, "created_at": "2017-12-04T19:42:36Z", "updated_at": "2017-12-04T19:42:36Z", "author_association": "CONTRIBUTOR", "body_html": "<p>Not sure what commit fixed this but it's definitely fixed in 0.3 :)</p>", "body_text": "Not sure what commit fixed this but it's definitely fixed in 0.3 :)", "body": "Not sure what commit fixed this but it's definitely fixed in 0.3 :)"}