{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/291644534", "html_url": "https://github.com/pytorch/pytorch/issues/39#issuecomment-291644534", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/39", "id": 291644534, "node_id": "MDEyOklzc3VlQ29tbWVudDI5MTY0NDUzNA==", "user": {"login": "soumith", "id": 1310570, "node_id": "MDQ6VXNlcjEzMTA1NzA=", "avatar_url": "https://avatars0.githubusercontent.com/u/1310570?v=4", "gravatar_id": "", "url": "https://api.github.com/users/soumith", "html_url": "https://github.com/soumith", "followers_url": "https://api.github.com/users/soumith/followers", "following_url": "https://api.github.com/users/soumith/following{/other_user}", "gists_url": "https://api.github.com/users/soumith/gists{/gist_id}", "starred_url": "https://api.github.com/users/soumith/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/soumith/subscriptions", "organizations_url": "https://api.github.com/users/soumith/orgs", "repos_url": "https://api.github.com/users/soumith/repos", "events_url": "https://api.github.com/users/soumith/events{/privacy}", "received_events_url": "https://api.github.com/users/soumith/received_events", "type": "User", "site_admin": false}, "created_at": "2017-04-04T21:59:21Z", "updated_at": "2017-04-04T21:59:21Z", "author_association": "MEMBER", "body_html": "<p>std::bad_cast when running <a href=\"https://gist.github.com/panovr/2977d9f26866b05583b0c40d88a315bf\">https://gist.github.com/panovr/2977d9f26866b05583b0c40d88a315bf</a> instead of a proper error message.<br>\nAs posted here: <a href=\"https://discuss.pytorch.org/t/runtimeerror-std-bad-cast-trying-to-fine-tune-resnet18/1592\" rel=\"nofollow\">https://discuss.pytorch.org/t/runtimeerror-std-bad-cast-trying-to-fine-tune-resnet18/1592</a></p>", "body_text": "std::bad_cast when running https://gist.github.com/panovr/2977d9f26866b05583b0c40d88a315bf instead of a proper error message.\nAs posted here: https://discuss.pytorch.org/t/runtimeerror-std-bad-cast-trying-to-fine-tune-resnet18/1592", "body": "std::bad_cast when running https://gist.github.com/panovr/2977d9f26866b05583b0c40d88a315bf instead of a proper error message.\r\nAs posted here: https://discuss.pytorch.org/t/runtimeerror-std-bad-cast-trying-to-fine-tune-resnet18/1592"}