{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/349021474", "html_url": "https://github.com/tensorflow/tensorflow/pull/13012#issuecomment-349021474", "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/13012", "id": 349021474, "node_id": "MDEyOklzc3VlQ29tbWVudDM0OTAyMTQ3NA==", "user": {"login": "alextp", "id": 5061, "node_id": "MDQ6VXNlcjUwNjE=", "avatar_url": "https://avatars0.githubusercontent.com/u/5061?v=4", "gravatar_id": "", "url": "https://api.github.com/users/alextp", "html_url": "https://github.com/alextp", "followers_url": "https://api.github.com/users/alextp/followers", "following_url": "https://api.github.com/users/alextp/following{/other_user}", "gists_url": "https://api.github.com/users/alextp/gists{/gist_id}", "starred_url": "https://api.github.com/users/alextp/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/alextp/subscriptions", "organizations_url": "https://api.github.com/users/alextp/orgs", "repos_url": "https://api.github.com/users/alextp/repos", "events_url": "https://api.github.com/users/alextp/events{/privacy}", "received_events_url": "https://api.github.com/users/alextp/received_events", "type": "User", "site_admin": false}, "created_at": "2017-12-04T16:42:43Z", "updated_at": "2017-12-04T16:42:43Z", "author_association": "MEMBER", "body_html": "<p>It claimed an infrastructure error so let's try again.</p>", "body_text": "It claimed an infrastructure error so let's try again.", "body": "It claimed an infrastructure error so let's try again."}