{"url": "https://api.github.com/repos/tensorflow/tensorflow/pulls/comments/139250786", "pull_request_review_id": 63161767, "id": 139250786, "node_id": "MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDEzOTI1MDc4Ng==", "diff_hunk": "@@ -431,6 +431,39 @@ TEST_F(GradientsTest, UnreachableEdgeGradTwoOutputs) {\n       outputs[0], test::AsTensor<double>({17.5, 24.7, 26.8}, {3, 1}), 1e-5);\n }\n \n+TEST_F(GradientsTest, UnreachableInput) {\n+  auto x = Variable(scope_test_, {2, 3}, DT_DOUBLE);\n+  auto x_const = Const(scope_test_, {{1.0, 2.0, 3.0}, {4.0, 5.0, 6.0}});\n+  auto x_assign = Assign(scope_test_, x, x_const);\n+\n+  auto y = Variable(scope_test_, {3, 1}, DT_DOUBLE);\n+  auto y_const = Const(scope_test_, {{1.0}, {2.0}, {3.0}});\n+  auto y_assign = Assign(scope_test_, y, y_const);\n+\n+  auto m1 = MatMul(scope_test_, x, y);\n+\n+  auto z = Variable(scope_test_.WithOpName(\"z\"), {1, 3}, DT_DOUBLE);\n+  auto z_const = Const(scope_test_, {{9.0, 10.0, 11.0}});\n+  auto z_assign = Assign(scope_test_, z, z_const);\n+\n+  auto m2 = MatMul(scope_test_, y, z);\n+\n+  auto dm1 = Const(scope_test_, {{0.5}, {0.5}});\n+  auto dm2 =\n+      Const(scope_test_, {{0.5, 0.5, 0.5}, {0.6, 0.7, 0.8}, {0.6, 0.7, 0.9}});\n+\n+  std::vector<Output> grad_outputs;\n+  // from m1 z is unreachable, an error status should be returned\n+  //   m2  m1\n+  //   |   |\n+  //   *   *\n+  //  / \\ / \\\n+  // z   y   x\n+  Status status = AddSymbolicGradients(scope_test_, {m1}, {z}, {dm1}, nullptr);\n+  EXPECT_EQ(status.code(), error::INVALID_ARGUMENT);\n+  EXPECT_EQ(status.error_message(), \"z is unreachable from the output(s).\");", "path": "tensorflow/cc/framework/gradients_test.cc", "position": null, "original_position": 34, "commit_id": "a330e9fd0f5a0ffeec3a7307c3a8db80e35588da", "original_commit_id": "9c24b0a71de6b7eed2800dd2e41f5097379a8202", "user": {"login": "skye", "id": 88808, "node_id": "MDQ6VXNlcjg4ODA4", "avatar_url": "https://avatars1.githubusercontent.com/u/88808?v=4", "gravatar_id": "", "url": "https://api.github.com/users/skye", "html_url": "https://github.com/skye", "followers_url": "https://api.github.com/users/skye/followers", "following_url": "https://api.github.com/users/skye/following{/other_user}", "gists_url": "https://api.github.com/users/skye/gists{/gist_id}", "starred_url": "https://api.github.com/users/skye/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/skye/subscriptions", "organizations_url": "https://api.github.com/users/skye/orgs", "repos_url": "https://api.github.com/users/skye/repos", "events_url": "https://api.github.com/users/skye/events{/privacy}", "received_events_url": "https://api.github.com/users/skye/received_events", "type": "User", "site_admin": false}, "body": "I think this error message could provide some more context, maybe:\r\nCannot compute the partial derivative for node 'z' as it's unreachable from the output node(s).", "created_at": "2017-09-15T21:08:45Z", "updated_at": "2017-09-18T15:29:23Z", "html_url": "https://github.com/tensorflow/tensorflow/pull/13071#discussion_r139250786", "pull_request_url": "https://api.github.com/repos/tensorflow/tensorflow/pulls/13071", "author_association": "MEMBER", "_links": {"self": {"href": "https://api.github.com/repos/tensorflow/tensorflow/pulls/comments/139250786"}, "html": {"href": "https://github.com/tensorflow/tensorflow/pull/13071#discussion_r139250786"}, "pull_request": {"href": "https://api.github.com/repos/tensorflow/tensorflow/pulls/13071"}}, "body_html": "<p>I think this error message could provide some more context, maybe:<br>\nCannot compute the partial derivative for node 'z' as it's unreachable from the output node(s).</p>", "body_text": "I think this error message could provide some more context, maybe:\nCannot compute the partial derivative for node 'z' as it's unreachable from the output node(s)."}